services:
  - type: web
    name: aboutmepy
    runtime: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
